# Generated by Django 2.1.7 on 2019-03-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
